name: jpf-run

on:
  push:
  workflow_dispatch:

jobs:
  jpf-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Executes JPF
        run: |
          echo "javac version: `javac --version`"
          git clone https://github.com/javapathfinder/jpf-core.git
          pushd jpf-core
          ./gradlew buildJars
          popd
          mkdir app/bin
          find app/src/main/java/pcd/lab02 -name "*.java" | xargs javac -d app/bin -cp jpf-core/build/jpf-classes.jar
          ls app/bin
          for jpfFile in $(ls app/src/main/jpf/*.jpf); do
            echo "JPF: $jpfFile"
            java -jar jpf-core/build/RunJPF.jar $jpfFile
          done
