name: jpf-run

on:
  push:
  workflow_dispatch:


jobs:
  jpf-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Executes JPF
        run: |
          echo "javac version: `javac --version`"
          ls
          mkdir app/bin
          javac -d app/bin -cp lib app/src/main/java/pcd/lab02/*.java
          for jpfFile in $(ls app/src/main/jpf/*.jpf); do
            echo "JPF: $jpfFile"
            java -jar lib/RunJPF.jar $jpfFile
          done
